### PR TITLE
Use standard library data-structures, instead of rustc structures, in cbmc crate.

### PR DESCRIPTION
**Pull request by danielsn**
### Description of changes: 

Currently, the CBMC crate uses data-structures from the compiler.
This creates unnecessary coupling and will make it harder to seperate into a seperate crate.
Instead, use the `std` structures.

### Resolved issues:

Resolves #ISSUE-NUMBER

### Call-outs:

The `x.py` build raises a warning if you use `std::collections::HashMap` instead of the `FxHashMap` from the compiler crate.
This should go away once we move to regular cargo.

Also, this might be slightly slower, as std uses a (slightly slower) randomized hash function than the main compiler.
We can profile, but this should not be a major issue.

### Testing:

* How is this change tested? Existing reg tests

* Is this a refactor change? Yes

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by tedinski — APPROVED** [review]
lgtm, it'd be nice to check runtime and memory usage before/after.

**Comment by danielsn** [comment]
New cbmc:
```
        Command being timed: "scripts/std-lib-regression.sh"
        User time (seconds): 76.61
        System time (seconds): 65.14
        Percent of CPU this job got: 187%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:15.70
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 969192
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 10996
        Minor (reclaiming a frame) page faults: 1262906
        Voluntary context switches: 1069
        Involuntary context switches: 39062
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 6
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by danielsn** [comment]
old
```
        Command being timed: "scripts/std-lib-regression.sh"
        User time (seconds): 77.41
        System time (seconds): 65.85
        Percent of CPU this job got: 188%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:16.10
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 955544
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 1240
        Minor (reclaiming a frame) page faults: 1270353
        Voluntary context switches: 355
        Involuntary context switches: 41362
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 8
        Page size (bytes): 4096
        Exit status: 0
```

So same timing, 1% increase in memory usage, which is basically noise.

**Review by zhassan-aws — APPROVED** [review]
If the default hasher for `HashMap` and `HashSet` cause performance issues in the future, we can switch to a more efficient hasher, such as `FxHasher` that `FxHashMap` and `FxHashSet` used.

**Pull request merged**
